{"time":"2024-11-06T20:49:27.8078597+05:30","level":"INFO","msg":"using version","core version":"0.18.5"}
{"time":"2024-11-06T20:49:27.8078597+05:30","level":"INFO","msg":"created symlink","path":"E:\\FYP_review2_ref\\FYP_review2\\project_root\\wandb\\run-20241106_204927-c5sv9q6q\\logs\\debug-core.log"}
{"time":"2024-11-06T20:49:28.2319192+05:30","level":"INFO","msg":"created new stream","id":"c5sv9q6q"}
{"time":"2024-11-06T20:49:28.2324493+05:30","level":"INFO","msg":"stream: started","id":"c5sv9q6q"}
{"time":"2024-11-06T20:49:28.2324493+05:30","level":"INFO","msg":"sender: started","stream_id":"c5sv9q6q"}
{"time":"2024-11-06T20:49:28.2324493+05:30","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"c5sv9q6q"}}
{"time":"2024-11-06T20:49:28.2324493+05:30","level":"INFO","msg":"handler: started","stream_id":{"value":"c5sv9q6q"}}
{"time":"2024-11-06T20:49:28.895294+05:30","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-11-06T23:44:23.9858542+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.10.100.94:65197->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
